---
- name: Import key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
  tags: install

- name: Add mongo repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install mongo package
  apt:
    name: mongodb-org
    update_cache: yes
  tags: install

- name: Mongo started and enabled
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
