---
- hosts: all
  become: yes
  tasks:
  - name: Add mongo repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongo package
    apt:
      name: mongodb-org
      update_cache: yes

  - name: Mongo started and enabled
    systemd:
      name: mongod
      enabled: yes
      state: started
